Allow user configs without custom image
staticfloat/docker-nginx-certbot pull request #12
Opened 2019-05-17 15:28 UTC by damiansilbergleithcunniff

I didn't want to build a new image every time I had a different set of sites that I want to front with nginx. This is especially useful if you have dev/test/stage setups and you just want to roll everything out using a common image.

To do this, I leveraged your startup scripts and just added a script that symlinks all configs in a source dir to /etc/nginx/conf.d. That way the certbot config can still live happily there alongside the rest of the config files.

All a user needs to do is put his/her configs into a directory and then mount it using a volume to /etc/nginx/user.conf.d. All *.conf files in that dir will be symlinked on startup.

> NOTE: this is a "redo" of a closed PR.  I worked the bugs out and cleaned it up to be more readable.

2019-05-25 02:53 UTC, damiansilbergleithcunniff commented
After testing in prod ;)  I discovered that the startup scripts are run too late.  By that point, nginx has crashed because there are no certs for the site files.

To remedy this I moved the functionality as a shell function into the utils and just call it explicitly at the start of the entrypoint.  If the user has no mounted files then a message is printed stating this and execution continues as if I had never modified the code.

2019-07-20 00:25 UTC, staticfloat requested changes

2019-07-20 00:25 UTC, staticfloat commented on README.md
> +          - ./conf.d:/etc/nginx/user.conf.d
Let's put `:ro` at the end of this, to ensure that user configuration is never clobbered by the scripts in this image.

2019-07-20 00:25 UTC, staticfloat commented on example/docker-compose.yml
> +      - ./conf.d:/etc/nginx/user.conf.d
`:ro` here too

2019-07-20 00:25 UTC, staticfloat commented on src/scripts/util.sh
> +    SOURCE_DIR=${1-/etc/nginx/user.conf.d}
Surround in quotes to allow for directories with spaces in them (yes, people that do that bring pain upon themselves, but let's be good neighbors)

2019-07-20 00:25 UTC, staticfloat commented on src/scripts/util.sh
> +            ln -s "${conf}" "${TARGET_DIR}/$(basename ${conf})"
I think it would be clearer to just pass `-v` to `ln`, then you can eliminate the `echo` above.

2019-07-20 00:26 UTC, staticfloat commented
All minor requests, this is a clear improvement over the previous setup, and best of all, it's backwards-compatible!

2019-08-24 18:28 UTC, karlkeefer commented on README.md
> +And a `.conf` file such as in that directory:
typo: rm `such as`

2019-08-24 18:32 UTC, karlkeefer commented
Excited about this repo & PR, and agree with the repo owner's review!
Looking forward to using this

2019-09-10 08:41 UTC, DDevine commented
I tested this pull request and it worked nicely for me. I look forward to just using this as an image in my docker-compose.yml
I tested it by specifying the git URI in `build:` and mounting my nginx conf in /etc/nginx/user.conf.d

2019-10-03 04:02 UTC, ds17f commented
Requests have been addressed.  Sorry to take so long to get back to this.  "Life is what happens when you're busy making other plans."

2019-11-19 09:57 UTC, merged

2019-11-19 09:57 UTC, staticfloat commented
Awesome!  Thanks